// PM2 Ecosystem — Unified Yaya Platform Process Management
// Manages all backend services, web apps, workers, and tunnels

module.exports = {
  apps: [
    {
      name: 'yaya-business',
      cwd: '/home/yaya/yaya_business/autobot',  // still points to original until full migration
      script: 'dist/index.js',
      interpreter: '/usr/bin/node',
      node_args: '--enable-source-maps',
      env: { PORT: 3000, NODE_ENV: 'production', SERVICE_NAME: 'yaya-business' },
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
      error_file: '/home/yaya/logs/yaya-business-error.log',
      out_file: '/home/yaya/logs/yaya-business-out.log',
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      restart_delay: 3000,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 10000,
      listen_timeout: 15000,
      shutdown_with_message: true,
      max_memory_restart: '2G',
    },
    {
      name: 'yaya-health',
      cwd: '/home/yaya/yaya_health',
      script: 'dist/index.js',
      interpreter: 'node',
      node_args: '--enable-source-maps',
      env: { PORT: 3100, NODE_ENV: 'production', SERVICE_NAME: 'yaya-health' },
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
      error_file: '/home/yaya/logs/yaya-health-error.log',
      out_file: '/home/yaya/logs/yaya-health-out.log',
      merge_logs: true,
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      restart_delay: 3000,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 10000,
      listen_timeout: 15000,
      shutdown_with_message: true,
      max_memory_restart: '1G',
    },
    {
      name: 'agente-ceo',
      cwd: '/home/yaya/yaya/apps/web',     // points to new monorepo app
      script: 'node_modules/.bin/next',
      args: 'start --port 3005',
      env: { NODE_ENV: 'production' },
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
      error_file: '/home/yaya/logs/agente-ceo-error.log',
      out_file: '/home/yaya/logs/agente-ceo-out.log',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
    {
      name: 'scraper-worker',
      cwd: '/home/yaya/yaya/workers/scraper-worker',
      script: 'dist/index.js',
      interpreter: 'node',
      env: { NODE_ENV: 'production' },
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
      error_file: '/home/yaya/logs/scraper-worker-error.log',
      out_file: '/home/yaya/logs/scraper-worker-out.log',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      max_memory_restart: '512M',
    },
    {
      name: 'hpc-tunnel',
      script: '/home/yaya/yaya/infra/scripts/hpc-tunnel.sh',
      interpreter: 'bash',
      autorestart: true,
      max_restarts: 999,
    },
  ],
};
